In [1]:
import pandas as pd
import numpy as np

data = pd.read_csv('Students.csv')
df = pd.DataFrame(data)
print(df)

    Student  Gender  StudyHours  Attendance  Math  English  Science
0     rawan  Female           5          92    90       86       89
1     Ahmed    Male           3          90    85       78       88
2      Mona  Female           5          95    92       89       94
3      Omar    Male           2          70    60       65       58
4      Sara  Female           6          98    96       94       97
5       Ali    Male           1          60    45       55       50
6      Nour  Female           4          85    80       91       86
7   Youssef    Male           3          75    72       68       74
8     Salma  Female           5          92    88       95       90
9    Khaled    Male           2          65    55       60       62
10    Farah  Female           4          88    84       82       89

In [2]:
df.loc[0]

Student        rawan
Gender        Female
StudyHours         5
Attendance        92
Math              90
English           86
Science           89
Name: 0, dtype: object

In [3]:
df.head(3)

  Student  Gender  StudyHours  Attendance  Math  English  Science
0   rawan  Female           5          92    90       86       89
1   Ahmed    Male           3          90    85       78       88
2    Mona  Female           5          95    92       89       94

In [4]:
df.tail(3)

   Student  Gender  StudyHours  Attendance  Math  English  Science
8    Salma  Female           5          92    88       95       90
9   Khaled    Male           2          65    55       60       62
10   Farah  Female           4          88    84       82       89

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Student     11 non-null     object
 1   Gender      11 non-null     object
 2   StudyHours  11 non-null     int64
 3   Attendance  11 non-null     int64
 4   Math        11 non-null     int64
 5   English     11 non-null     int64
 6   Science     11 non-null     int64
dtypes: int64(5), object(2)
memory usage: 744.0+ bytes

In [6]:
df.describe()

       StudyHours  Attendance       Math    English    Science
count   11.000000   11.000000  11.000000  11.000000  11.000000
mean     3.636364   82.727273  77.000000  78.454545  79.727273
std      1.566699   13.016074  16.792856  14.264387  16.094042
min      1.000000   60.000000  45.000000  55.000000  50.000000
25%      2.500000   72.500000  66.000000  66.500000  68.000000
50%      4.000000   88.000000  84.000000  82.000000  88.000000
75%      5.000000   92.000000  89.000000  90.000000  89.500000
max      6.000000   98.000000  96.000000  95.000000  97.000000

In [7]:
print(df.isnull().sum())
print("\n")
print(df.duplicated().sum())

Student       0
Gender        0
StudyHours    0
Attendance    0
Math          0
English       0
Science       0
dtype: int64


0

In [8]:
df["TotalScore"] = df["Math"] + df["English"] + df["Science"]
df

,Student,Gender,StudyHours,Attendance,Math,English,Science,TotalScore
0,rawan,Female,5,92,90,86,89,265
1,Ahmed,Male,3,90,85,78,88,251
2,Mona,Female,5,95,92,89,94,275
3,Omar,Male,2,70,60,65,58,183
4,Sara,Female,6,98,96,94,97,287
5,Ali,Male,1,60,45,55,50,150
6,Nour,Female,4,85,80,91,86,257
7,Youssef,Male,3,75,72,68,74,214
8,Salma,Female,5,92,88,95,90,273
9,Khaled,Male,2,65,55,60,62,177
10,Farah,Female,4,88,84,82,89,255

In [9]:
df ["AverageScore"] = (df["Math"] + df["English"] + df["Science"])/3
df

,Student,Gender,StudyHours,Attendance,Math,English,Science,TotalScore,AverageScore
0,rawan,Female,5,92,90,86,89,265,88.333333
1,Ahmed,Male,3,90,85,78,88,251,83.666667
2,Mona,Female,5,95,92,89,94,275,91.666667
3,Omar,Male,2,70,60,65,58,183,61.000000
4,Sara,Female,6,98,96,94,97,287,95.666667
5,Ali,Male,1,60,45,55,50,150,50.000000
6,Nour,Female,4,85,80,91,86,257,85.666667
7,Youssef,Male,3,75,72,68,74,214,71.333333
8,Salma,Female,5,92,88,95,90,273,91.000000
9,Khaled,Male,2,65,55,60,62,177,59.000000
10,Farah,Female,4,88,84,82,89,255,85.000000

In [10]:
sorted_df = df.sort_values("AverageScore",ascending=False,)
print(f"maximum three AverageScore\n{sorted_df.head(3)}")

maximum three AverageScore
  Student  Gender  StudyHours  Attendance  Math  English  Science  TotalScore  \
4    Sara  Female           6          98    96       94       97         287
2    Mona  Female           5          95    92       89       94         275
8   Salma  Female           5          92    88       95       90         273

   AverageScore
4     95.666667
2     91.666667
8     91.000000

In [11]:
df.groupby("Gender",group_keys=True)["AverageScore"].mean()

Gender
Female    89.555556
Male      65.000000
Name: AverageScore, dtype: float64

In [12]:
# Students who study 3 hours or less
low_study = df[df["StudyHours"] <= 3]

# Students who study more than 3 hours
high_study = df[df["StudyHours"] > 3]

print("Average score for 3 hours or less:")
print(low_study["AverageScore"].mean())

print("Average score for more than 3 hours:")
print(high_study["AverageScore"].mean())

Average score for 3 hours or less:
65.0
Average score for more than 3 hours:
89.55555555555556

In [14]:
df["StudyGroup"] = df["StudyHours"].apply(
    lambda x: "3 hours or less" if x <= 3 else "More than 3 hours"
)

print(df.groupby("StudyGroup")["AverageScore"].mean())

StudyGroup
3 hours or less      65.000000
More than 3 hours    89.555556
Name: AverageScore, dtype: float64

In [13]:
df.to_csv("students_analyzed.csv", index=False)